# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xmAUYTE8m2k4Pcamyi0coiM6LepC4bhr
"""

!pip install streamlit pyngrok seaborn plotly

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import streamlit as st
# 
# st.set_page_config(page_title="University Dashboard", layout="wide")
# 
# st.title("University Student Dashboard")
# 
# df = pd.read_csv("university_student_data.csv")
# 
# st.sidebar.header("Filters")
# 
# selected_year = st.sidebar.selectbox(
#     "Select Year",
#     sorted(df["Year"].unique())
# )
# 
# selected_term = st.sidebar.selectbox(
#     "Select Term",
#     df["Term"].unique()
# )
# 
# filtered_df = df[
#     (df["Year"] == selected_year) &
#     (df["Term"] == selected_term)
# ]
# 
# st.subheader("Key Metrics")
# 
# col1, col2 = st.columns(2)
# 
# average_retention = filtered_df["Retention Rate (%)"].mean()
# 
# average_satisfaction = filtered_df["Student Satisfaction (%)"].mean()
# 
# col1.metric(
#     "Retention Rate",
#     f"{average_retention:.1f}%"
# )
# 
# col2.metric(
#     "Satisfaction",
#     f"{average_satisfaction:.1f}%"
# )
# 
# st.subheader("Dataset Preview")
# 
# st.dataframe(filtered_df)
# 
# retention = df.groupby("Year")[
#     "Retention Rate (%)"
# ].mean().reset_index()
# 
# fig1, ax1 = plt.subplots(figsize=(10,5))
# 
# ax1.plot(
#     retention["Year"],
#     retention["Retention Rate (%)"],
#     marker='o'
# )
# 
# ax1.set_title("Retention Rate Over Time")
# 
# ax1.set_xlabel("Year")
# 
# ax1.set_ylabel("Retention Rate (%)")
# 
# ax1.grid(True)
# 
# st.pyplot(fig1)
# 
# fig2, ax2 = plt.subplots(figsize=(10,5))
# 
# sns.barplot(
#     data=df,
#     x="Year",
#     y="Student Satisfaction (%)",
#     ax=ax2
# )
# 
# ax2.set_title("Student Satisfaction by Year")
# 
# st.pyplot(fig2)
# 
# fig3, ax3 = plt.subplots(figsize=(8,5))
# 
# sns.barplot(
#     data=df,
#     x="Term",
#     y="Enrolled",
#     ax=ax3
# )
# 
# ax3.set_title("Spring vs Fall Enrollment")
# 
# st.pyplot(fig3)
# 
# applications = df.groupby("Year")[
#     "Applications"
# ].mean().reset_index()
# 
# fig4, ax4 = plt.subplots(figsize=(10,5))
# 
# sns.lineplot(
#     data=applications,
#     x="Year",
#     y="Applications",
#     marker='o',
#     ax=ax4
# )
# 
# ax4.set_title("Applications Over Time")
# 
# ax4.grid(True)
# 
# st.pyplot(fig4)
# 
# departments = [
#     "Engineering Enrolled",
#     "Business Enrolled",
#     "Arts Enrolled",
#     "Science Enrolled"
# ]
# 
# department_totals = filtered_df[departments].sum()
# 
# fig5, ax5 = plt.subplots(figsize=(8,8))
# 
# ax5.pie(
#     department_totals,
#     labels=[
#         "Engineering",
#         "Business",
#         "Arts",
#         "Science"
#     ],
#     autopct='%1.1f%%'
# )
# 
# ax5.set_title("Department Enrollment Distribution")
# 
# st.pyplot(fig5)
# 
# fig6, ax6 = plt.subplots(figsize=(10,6))
# 
# sns.heatmap(
#     df.corr(numeric_only=True),
#     annot=True,
#     cmap="Blues",
#     ax=ax6
# )
# 
# ax6.set_title("Correlation Heatmap")
# 
# st.pyplot(fig6)
# 
# st.caption("Interactive dashboard created with Streamlit")

!streamlit run app.py